server:
  port: ${FISH_DAS_PORT:9003}
  servlet:
    context-path: /das

spring:
  data:
    redis:
      url: redis://${REDIS_PASSWORD:123456}@${REDIS_ADDR:localhost}:6379/0
    mongodb:
      uri: mongodb://admin:123456@${MONGO_DB_ADDR:localhost}:27017/fish?authSource=fish
  application:
    name: fish-das
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost}:8848
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}

logging:
  config: classpath:logback.xml
  level:
    root: WARN
    com.fishsoup.fishdas: DEBUG
#  file:
#    path: ./logs
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}: %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}: %msg%n"

management:
  tracing:
    enabled: true
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_SERVER_ADDR:localhost}:9411/api/v2/spans