websocket:
  port: ${FISH_CHAT_PORT:9005}

server:
  port: 9004
  servlet:
    context-path: /chat

spring:
  application:
    name: fish-chat
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost}:8848
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
  data:
    redis:
      url: redis://${REDIS_PASSWORD:123456}@${REDIS_ADDR:localhost}:6379/0
      # 连接超时时间 3000 毫秒
      connect-timeout: 3000
      # 命令执行超时时间 3000 毫秒
      timeout: 3000

logging:
  config: classpath:logback.xml
  level:
    root: WARN
    com.fishsoup.fishchat: DEBUG