server:
  port: ${FISH_USER_PORT:9001}
  servlet:
    context-path: /user

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost}:8848
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
  config:
    import:
      - optional:nacos:zipkin-config.yml?refreshEnabled=true
  application:
    name: fish-user
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/db_fish?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: fish
    password: 123456
    #druid数据源配置
    druid:
      # 初始化连接池大小
      initialSize: 5
      # 最小连接数
      minIdle: 5
      # 最大连接数
      maxActive: 40
      # 获取连接时的最大等待时间
      maxWait: 60000
      #间隔多长时间进行一次检测；
      timeBetweenEvictionRunsMillis: 60000
      #配置一个最小的生存对象的空闲时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
      testOnReturn: false
      poolPreparedStatements: true
      #配置监控统计拦截的filters。stat：监控统计、wall：防御sql注入、log4j：日志记录
      filters: stat,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      #执行时间超过3000毫秒的sql会被标记为慢sql
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      #配置过滤器，过滤掉静态文件
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.css,*.gif,*.jpg,*.bmp,*.png,*.ico
      #配置可视化控制台页面
      stat-view-servlet:
        filter:
          stat:
            merge-sql: false
        enabled: true
        #访问德鲁伊监控页面的地址
        url-pattern: /druid/*
        #IP白名单 没有配置或者为空 则允许所有访问
        allow:
        #IP黑名单 若白名单也存在 则优先使用
        #deny: ip地址
        #禁用重置按钮
        reset-enable: true
        #登录所用的用户名与密码
        login-username: fish
        login-password: 123456
  data:
    redis:
      url: redis://${REDIS_PASSWORD:123456}@${REDIS_ADDR:localhost}:6379/0
      # 连接超时时间 3000 毫秒
      connect-timeout: 3000
      # 命令执行超时时间 3000 毫秒
      timeout: 3000

base:
  config:
    mdb:
      hostname: ${MYSQL_ADDR:localhost}
      dbname: db_fish
      port: 3306
      username: fish
      password: 123456

seata:
  enabled: true
  application-id: fish-user
  tx-service-group: fish-user-tx-group
  config:
    type: nacos
    nacos:
      serverAddr: ${NACOS_SERVER_ADDR:localhost}:8848
      dataId: "seata.properties"
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${NACOS_SERVER_ADDR:localhost}:8848
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      group: SEATA_GROUP
      cluster: default
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      paas-protocol-group: default

management:
#  tracing:
#    enabled: true
#    sampling:
#      probability: 0.1
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_SERVER_ADDR:localhost}:9411/api/v2/spans